[package]
name = "front-end-compiler"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lexer"
path = "src/lexer/main.rs"

[[bin]]
name = "sintatico"
path = "src/syntactic/main.rs"

[lib]
name = "compiler"
path = "src/lib.rs"

[dependencies]
strum = "0.27"
strum_macros = "0.27"
